# Zeros and Ones
# **Task**:

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.


In [ ]:
import numpy

lst = list(map(int, input().split()))

print("OUTPUT IS: ")
print(numpy.zeros(lst, dtype = numpy.int))                   

print(numpy.ones(lst, dtype = numpy.int))

3 3 3
OUTPUT IS: 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


<ipython-input-2-69ac8776b5bc>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros(lst, dtype = numpy.int))
<ipython-input-2-69ac8776b5bc>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20;

# Shape and Reshape
# **Task**:

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.



In [1]:
import numpy

lst = list(map(int, input().split()))
my_array = numpy.array(lst)
print(numpy.reshape(my_array,(3,3)))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Eye and Identity
# **Task**:

Your task is to print an array of size N X M with its main diagonal elements as 0's and 1's everywhere else.


In [2]:
import numpy
n, m = (map(int, input().split()))

numpy.set_printoptions(legacy = '1.13')

print(numpy.eye(n, m, k = 0))


8 7
[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
